### ISSUE TITLE
Broken in react 15.4.0

### ISSUE THREAD

**Issue by Gertt** [ambassify/reon#4]
React 15.4.0 split up react and react-dom, so 

```
import PooledClass from 'react/lib/PooledClass';
import ReactEvent from 'react/lib/SyntheticEvent';
```

are not available anymore and shoud be imported from `react-dom`. Don't know about backwards compatibility but I think it should work.

**Comment by JorgenEvens** [comment]
Since the latest release of `reon` feels stable we should maybe just cut a new version with a major version bump which only supports react `react >= 15.4`.

**Comment by Gertt** [comment]
Agreed to by the team, we will cute v2 with `react >= 15.4`
